stages:
  - build
  - deploy

variables:
  REGISTRY: "gitlab.control.lth.se:5050"
  IMAGE_NAME: "regler/frtn90/2025/agroup01"

build:stock-generator:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker build -t $REGISTRY/$IMAGE_NAME/stock-generator:$CI_COMMIT_SHA stock-generator/
    - docker push $REGISTRY/$IMAGE_NAME/stock-generator2:$CI_COMMIT_SHA

build:alert-engine:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker build -t $REGISTRY/$IMAGE_NAME/alert-engine:$CI_COMMIT_SHA alert-engine/
    - docker push $REGISTRY/$IMAGE_NAME/alert-engine2:$CI_COMMIT_SHA

build:backend-api:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker build -t $REGISTRY/$IMAGE_NAME/backend-api:$CI_COMMIT_SHA backend-api/
    - docker push $REGISTRY/$IMAGE_NAME/backend-api2:$CI_COMMIT_SHA

build:frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker build -t $REGISTRY/$IMAGE_NAME/frontend:$CI_COMMIT_SHA frontend/
    - docker push $REGISTRY/$IMAGE_NAME/frontend2:$CI_COMMIT_SHA

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  only:
    - main
  script:
    - kubectl config use-context <your-cluster-context>
    - kubectl set image deployment/stock-generator stock-generator=$REGISTRY/$IMAGE_NAME/stock-generator:$CI_COMMIT_SHA -n cloud-stock-watcher
    - kubectl set image deployment/alert-engine alert-engine=$REGISTRY/$IMAGE_NAME/alert-engine:$CI_COMMIT_SHA -n cloud-stock-watcher
    - kubectl set image deployment/backend-api backend-api=$REGISTRY/$IMAGE_NAME/backend-api:$CI_COMMIT_SHA -n cloud-stock-watcher
    - kubectl set image deployment/frontend frontend=$REGISTRY/$IMAGE_NAME/frontend:$CI_COMMIT_SHA -n cloud-stock-watcher
    - kubectl rollout status deployment/stock-generator -n cloud-stock-watcher