services:
  - type: web
    name: stock-watcher-api
    env: python
    buildCommand: pip install -r backend-api/requirements.txt
    startCommand: cd backend-api && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: "8000"

  - type: worker
    name: stock-watcher-alert-engine
    env: python
    buildCommand: pip install -r alert-engine/requirements.txt
    startCommand: cd alert-engine && python worker.py


  - type: worker
    name: stock-watcher-generator
    env: python
    buildCommand: pip install -r stock-generator/requirements.txt
    startCommand: cd stock-generator && python worker.py
    envVars:
      - key: STOCK_SYMBOLS
        value: TSLA,AAPL,MSFT,NVDA,GOOG
      - key: UPDATE_PERIOD
        value: "15"
