apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-generator
  namespace: cloud-stock-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-generator
  template:
    metadata:
      labels:
        app: stock-generator
    spec:
      containers:
        - name: stock-generator
          image: gitlab.control.lth.se:5050/regler/frtn90/2025/agroup01/stock-generator:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASS
              value: "guest"
            - name: STOCK_SYMBOLS
              value: "TSLA,AAPL,MSFT,NVDA,GOOG"
            - name: UPDATE_PERIOD
              value: "5.0"
