---
- name: Deploy Cloud Stock Watcher
  hosts: local
  gather_facts: no

  tasks:
    - name: Create namespace
      command: kubectl apply -f k8s/namespace.yaml
      args:
        chdir: "{{ playbook_dir }}/.."

    - name: Deploy application manifests
      command: kubectl apply -f k8s/
      args:
        chdir: "{{ playbook_dir }}/.."
