---
- name: Teardown Cloud Stock Watcher
  hosts: local
  gather_facts: no

  tasks:
    - name: Delete application manifests
      command: kubectl delete -f k8s/
      args:
        chdir: "{{ playbook_dir }}/.."
      ignore_errors: yes
